//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAssessmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSESSMENT_LINK
    {
        public ASSESSMENT_LINK()
        {
            this.ASSESSMENT_DATA = new HashSet<ASSESSMENT_DATA>();
        }
    
        public string RANDOM_STRING { get; set; }
        public string OUTCOMES { get; set; }
        public string DEPARTMENT_CD { get; set; }
        public string INSTRUCTOR_EMAILID { get; set; }
        public Nullable<bool> LINK_STATUS { get; set; }
    
        public virtual ICollection<ASSESSMENT_DATA> ASSESSMENT_DATA { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual USER_INFO USER_INFO { get; set; }
    }
}
