//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAssessmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENT
    {
        public DEPARTMENT()
        {
            this.ASSESSMENT_DATA = new HashSet<ASSESSMENT_DATA>();
            this.RUBRICS_DATA = new HashSet<RUBRICS_DATA>();
        }
    
        public string DEPARTMENT_CD { get; set; }
        public string department_desc { get; set; }
    
        public virtual ICollection<ASSESSMENT_DATA> ASSESSMENT_DATA { get; set; }
        public virtual ICollection<RUBRICS_DATA> RUBRICS_DATA { get; set; }
    }
}
