//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITAssessmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RUBRICS_DATA
    {
        public RUBRICS_DATA()
        {
            this.ASSESSMENT_DATA = new HashSet<ASSESSMENT_DATA>();
        }
      
        public int RUBRIC_ROWID { get; set; }

        [Display(Name = "Outcome")]
        [Required]
        public string OUTCOMES { get; set; }

        [Display(Name = "Department")]
        [Required]
        public string DEPARTMENT_CD { get; set; }

        [Display(Name = "Performance Indicator")]
        [Required]
        public string PERFORMANCE_INDICATOR { get; set; }

        [Display(Name = "Topic Name")]
        [Required]
        public string TOPIC { get; set; }

        [Display(Name = "Poor")]
        public string POOR { get; set; }

        [Display(Name = "Developing")]
        public string DEVELOPING { get; set; }

        [Display(Name = "Developed")]
        public string DEVELOPED { get; set; }

        [Display(Name = "Exemplary")]
        public string EXEMPLARY { get; set; }
    
        public virtual ICollection<ASSESSMENT_DATA> ASSESSMENT_DATA { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
    }
}
